name: fitloch
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Libraries
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.0
  workmanager: ^0.5.2
  flutter_background: ^1.3.0+1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^8.17.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  fl_chart: ^0.70.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets declaration
  assets:
    - assets/icon/   # Include this line to tell Flutter about the asset directory
    - assets/leaves_pattern.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/abstract.png" # Ensure this is the correct path to your icon image
