// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALfRKCB8PlKOs31VffJ6aUH1g7wiBaXpU',
    appId: '1:596308585072:web:4116e2980f790f36e122b5',
    messagingSenderId: '596308585072',
    projectId: 'fitloch-7c6c7',
    authDomain: 'fitloch-7c6c7.firebaseapp.com',
    storageBucket: 'fitloch-7c6c7.firebasestorage.app',
    measurementId: 'G-868EPVD654',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcanMfecIbPNI9_WYMPx2umtTtfcOvl0Q',
    appId: '1:596308585072:android:d68a535ebe399e06e122b5',
    messagingSenderId: '596308585072',
    projectId: 'fitloch-7c6c7',
    storageBucket: 'fitloch-7c6c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlxfywDstVHHkO5uv6rDIjW1qAVeJCIE',
    appId: '1:596308585072:ios:0a7a2647aa46a8dee122b5',
    messagingSenderId: '596308585072',
    projectId: 'fitloch-7c6c7',
    storageBucket: 'fitloch-7c6c7.firebasestorage.app',
    iosClientId: '596308585072-fsknr4bo0pl45llb1j35nb51k49ne1b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitloch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZlxfywDstVHHkO5uv6rDIjW1qAVeJCIE',
    appId: '1:596308585072:ios:0a7a2647aa46a8dee122b5',
    messagingSenderId: '596308585072',
    projectId: 'fitloch-7c6c7',
    storageBucket: 'fitloch-7c6c7.firebasestorage.app',
    iosClientId: '596308585072-fsknr4bo0pl45llb1j35nb51k49ne1b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitloch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALfRKCB8PlKOs31VffJ6aUH1g7wiBaXpU',
    appId: '1:596308585072:web:6452899cf05f6b20e122b5',
    messagingSenderId: '596308585072',
    projectId: 'fitloch-7c6c7',
    authDomain: 'fitloch-7c6c7.firebaseapp.com',
    storageBucket: 'fitloch-7c6c7.firebasestorage.app',
    measurementId: 'G-EP12N1N39J',
  );

}